### PR TITLE
Added fuzzy tests for parsing string representations of coordinates. …

### PR DESCRIPTION
**Pull request by B4rrCH**
…Tests for parsing result being "close enough".

### CODE REVIEW

**Comment by Tronald** [comment]
CLA: On File

@B4rrCH Can you address the following:

* In .NET Framework, string hashes are the same between executions.
* In .NET Core, string hashes change between executions.

[See Here](https://andrewlock.net/why-is-string-gethashcode-different-each-time-i-run-my-program-in-net-core/)

1. As the Unit Tests were built in core, `"CoordinateSharp".GetHashCode()` will produce a different seed with each execution, which I believe defeats the purpose of the seed. Is this by design? If so can you explain the reasoning behind it and if not, can you update to assign a consistent seed (even if it's just a randomly typed number defined by you). 

I had to look this one up as I noticed the seed kept changing. I just learned something new. Core still catches me with random things like this.

**Comment by B4rrCH** [comment]
@Tronald Huh, I did not know that either and did not actually check this, as I was used to the .NET Framework way of deterministic hash codes. The intent was indeed for it to be a constant. Do you have any preferences for seeds or is 0 alright?

**Comment by Tronald** [comment]
Perfect, 0 is fine. Thanks for updating. I just wanted to be sure, but I figured it was the Core change. Took me a while to figure it out so don't feel bad.

**Comment by B4rrCH** [comment]
Thanks for telling me about this, I doubt I would have found out about it until it would have broken something.

I'm also currently learning about why this was changed, it's apparently to fend of DoS attacks for web-apps (by creating hash-collisions). It has been presented at 28C3 ([VoD of the Talk](https://www.youtube.com/watch?v=R2Cq3CLI6H8) and [description on the CCC homepage](https://fahrplan.events.ccc.de/congress/2011/Fahrplan/events/4680.en.html)).

**Comment by Tronald** [comment]
I wasn't sure why this changed either, but it seemed like a pretty dramatic change so it's good to know why. Thanks for sharing. The Core changes have caught me a few times.  0 is now roundtrippable which caused a bug in this library causing coordinate strings to show -0 sometimes. That one took me a long time to figure out!

**Pull request merged**
