### PR TITLE
Support for a precision parameter in `ToRoundedString`

### PR DESCRIPTION
**Pull request by cervengoc**
See issue #208

### CODE REVIEW

**Comment by cervengoc** [comment]
Extended the PR with supporting a custom `IFormatProvider` for example for culture-agnostic double formatting.
Also, I think it could be a good idea to remove the `ToCentimeterString` method as now we have a more robust and flexible one, so I suggest deprecating it (added the `Obsolete` attribute with the proper message). But feel free to challenge this idea.

**Comment by Tronald** [comment]
Thanks for the update and your hard work on this. I agree deprecation of `ToCentimeterString()` makes sense. A few notes:

-For standardization we will want to include `ToRoundedString()` and deprecate `ToCentimeterString()` in the `MilitaryGridReferenceSystem` class as well.

-Regarding the `IFormatProvider` overload. I am hesitant to include this unless we include it in all relevant areas for standardization. Lat/Long, UTM, MGRS, ECEF, Cartesian, and Web Mercator all make use of decimal formatted number strings. Correct me if I am wrong, but strings should automatically display in the user's culture correct? The only reason for this overload would be to force a specified cultural format.

While this feature isn't crucial, I do think it would be convenient, especially for users wishing to test outputs in various cultures in their programs. Let me think on this one for a bit, as I think it would be worth while to create overloads in each system that allow a `IFormatProvider`. I also wonder if we should create a Global setting so it can be set once at application startup.

Let me know your thoughts.

**Comment by cervengoc** [comment]
Regarding your points,

- Yes, I agree it should be consistent between these two features. I've been focusing too much on UTM as we use that in our application. I'll include it in the MGRS part as well.
- I see your points about `IFormatProvider`. It would definitely be a good enhancement I think, but according to your description, I don't have the time for the complete and correct implementation. Also, I agree that it's kind of an edge case and the flexibility is not needed most of the time. I can see two benefits: desktop applications with different cultures but still needing a standard, deterministic format of coordinates; and unit tests run on developer machines. But overall I think I'm gonna revert that part for now.

Thank you for the detailed review.

**Comment by Tronald** [comment]
Great!

If you want to adjust the MGRS and remove the `IFormatProvider` overload in the UTM we can get the ball rolling. We will add the `IFormatProvider`  on our end when time permits. I think it's a great idea that should be pursued, but understand you do not have time to add.

We appreciate what you have been able to contribute greatly! 

I think these will be useful changes for the library.

**Comment by cervengoc** [comment]
So based on our discussion

- I've reverted the `IFormatProvider` support from UTM
- Added the same `ToRoundedString` refactor to MGRS
  - I payed attention that there was a `00000` padded format string for the whole number part, although I could not produce a test case for it.

**Comment by Tronald** [comment]
@cervengoc sorry for the delay in addressing this. I just realized this PR is targeting the master branch. Would you be able to resubmit and target the [develop](https://github.com/Tronald/CoordinateSharp/tree/develop) branch.

**Comment by Tronald** [comment]
Remapped PR to develop branch and merged. We still need to update documentation and give it a final review. Once complete we will push a release.

Thanks for the contribution!

**Comment by Tronald** [comment]
@cervengoc One quick question.

Can you further explain why you elected to not use the built in `Math.Round(double, int)`, and instead created your own rounding function in `MathHelp.cs`?

**Comment by Tronald** [comment]
@cervengoc we deleted `MathHelp.cs` and instead created an extension. [2.16.1.1](https://github.com/Tronald/CoordinateSharp/releases/tag/v2.16.1.1) includes your contribution, but for some reason it is not showing you in the contributors list (even though we can see your commit trail in the merge).

Looking at your contribution map, your pull request is made before your fork generation some how, so I am not sure if something is glitching out. I reviewed this support doc to see if there were any clues, but I didn't see anything: https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile/managing-contribution-settings-on-your-profile/why-are-my-contributions-not-showing-up-on-my-profile

I am hoping it eventually corrects as I have seen github take time to update contributors, but my apologies if it does not. You may not care, but I like to ensure contributors receive credit for their work.

**Comment by cervengoc** [comment]
Hi @Tronald , I apologize for the long break, I'm having kind of a busier period both at work and in life.
Thank you very much for finalizing the changes and including them in the release.

**Pull request merged**
