### PR TITLE
Add "EagerLoad" option as parameter for TryParse methods

### PR DESCRIPTION
**Pull request by mohammad4x**
I had performance problems with TryParse! I had a List of 1000 geo points in string which was taking 7500ms to parse with TryParse!
So I've added EagerLoad option to TryParse and then I achieved 24ms for 1000 geo points.

### CODE REVIEW

**Comment by mohammad4x** [comment]
#126

**Comment by Tronald** [comment]
Thank you for investigating and raising this issue. It is a great suggestion and we want to get this feature into the library as soon as possible.

With that said we have a few issues that need to be addressed, and we want to discuss them with you to see how you want to handle this. The first couple are standard, but the last is specific to you.

1. Pull requests need to be made to the [develop branch](https://github.com/Tronald/CoordinateSharp/tree/develop) as the master only contains our latest stable release.
2. We require a [Contributor License Agreement](https://github.com/Tronald/CoordinateSharp/blob/develop/Signature%20Group%20Contributor%20Agreement.pdf) to be signed by all our contributors.
3. Signature Group, LLC is a USA based company. Since it appears you are located in Iran, we aren't sure if we are allowed to accept contribution to the code base or issue commercial licenses in return for contribution as stated in our [Contribution Guidelines](https://github.com/Tronald/CoordinateSharp/blob/develop/CONTRIBUTING.md). Because CoordinateSharp is split licensed, accepting the PR may effect our Commercial Version. We are going to submit an inquiry with OFAC to determine what we are allowed to do before moving foward. 

If you wish though, we can just implement this feature ourselves. I believe this would be faster than waiting for answers from various organizations on what we as a USA based company are legally allowed to do. You are also allowed to use your forked version under the public domain AGPL 3.0. You also have the option to resubmit the PR into the develop branch, but we will have to wait for resolution and we aren't sure how long it will take.

We hope you understand and we want you to know we greatly appreciate you helping the library grow and certainly credit you for bringing this issue up. Eager loading options during parsing is a great suggestion for this library and we want to get it in place . Unfortunately, we have to protect our legal interests as well so this may take some time to workout.

Kind Regards

-Justin

**Comment by Tronald** [comment]
OFAC Inquiry has been submitted.

**Comment by mohammad4x** [comment]
Hi again :)

1- I'm sorry about that, i'm a rookie in open source community and  i just read the Github help on making forks and pull request. apparently i did it wrong!
2- As i was saying latter, i didn't know this either, Oops :(
3- I'm aware of the political conflicts between USA and Iran(also didn't know you were US based company). You're right, it's not worth it to take the risk, appreciate your time for the answer :)

I won't make another pull request for develop branch, you can take my fork as a suggestion and implement it yourself. i'll be using my fork in my project and wait for your next release.

You can cancel OFAC Inquiry too, i'm not in a rush for this feature.

Thanks.

**Comment by Tronald** [comment]
Thank you so much for understanding! I just want to state again that we really do appreciate your contribution regardless of these situations that are beyond our control. We should have this feature out within the next couple of weeks.

Kind Regards

**Pull request closed without merging**
